version: '3.4'

services:
  shoppingcart:
    image: shoppingcart
    build:
      context: client
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 5001:5001
