version: "3.9"
services:
  web:
    image: maelchan/shopthiscartserver
    ports:
      - 5001:5001
    environment:
      DB: ${DB}
  client:
    image: maelchan/shopthiscartclient
    ports:
      - 1234:1234
    environment:
      FAST_REFRESH: false