version: '3'
services:
  mongodb:
    image: mongo
    ports: 
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=team8
      - MONGO_INITDB_ROOT_PASSWORD=vyYuchd5rV2QAb0k
  mongo-express:
      image: mongo-express
      ports:
      - 8080:8081
      environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=team8
      - ME_CONFIG_MONGODB_ADMINPASSWORD=vyYuchd5rV2QAb0k
      - ME_CONFIG_MONGODB_SERVER=mongodb